services:
  - type: web
    name: bmu-canteen
    env: node
    plan: free
    region: oregon
    buildCommand: npm run render-build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
